### ISSUE TITLE
RuntimeError: memory error in alloc

### ISSUE THREAD

**Issue by CuiYan27** [sony/NDJIR#5]
**Thanks for your great work! 
I tried to train the NDJIR, but have some problems. I am not sure how to check and what's wrong with it. 
I use 384 DTU datasets download from official website and try to run command:**
_python python/train.py --config-name default \
    device_id=0 \
    monitor_base_path=/media/veilytech/disk1/Code/NDJIR/outputs \
    data_path=/media/veilytech/disk1/Code/NDJIR/data/DTU/scan69_

**error message is:**
![2024-03-01_14-43](https://github.com/sony/NDJIR/assets/67808446/da61b020-6f8f-43ee-b38a-d0500dc3427b)

**Here is detail message:** 
2024-03-01 14:35:13,126 [nnabla][INFO]: Initializing CPU extension...
python/train.py:178: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  hydra_main = hydra.main(config_path=args.config_path, config_name=args.config_name)
/home/veilytech/miniconda3/envs/ndjir/lib/python3.8/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  ret = run_job(
[2024-03-01 14:35:15,352][nnabla][INFO] - Initializing CUDA extension...
[2024-03-01 14:35:15,353][nnabla][INFO] - Initializing cuDNN extension...
[2024-03-01 14:35:15,353][nnabla][INFO] - Monitor Path: /media/veilytech/disk1/Code/NDJIR/outputs_scan69
[2024-03-01 14:35:15,353][nnabla][INFO] - DataSource with shuffle(True)
[2024-03-01 14:35:15,694][nnabla][INFO] - --- Finish loading dataset (scan69). ---
[2024-03-01 14:35:15,694][nnabla][INFO] - Num. of images = 49
[2024-03-01 14:35:15,694][nnabla][INFO] - Num. of pixels (H x W) = 147456 (384 x 384)
[2024-03-01 14:35:15,694][nnabla][INFO] - Num. of random rays = 512
[2024-03-01 14:35:15,694][nnabla][INFO] - Using DataIterator
Failed to allocate. Freeing memory cache and retrying.
Failed to allocate again.
Error during forward propagation:
  MulScalarCuda
  ExpCuda
  MaximumScalarCuda
  MinimumScalarCuda
  ReshapeCuda
  RandCuda
  RandCuda
  Callback
  ReshapeCuda
  ReshapeCuda
  Mul2Cuda
  ReshapeCuda
  CosCuda
  SinCuda
  ConcatenateCuda
  Callback
  ConcatenateCuda
  AffineCuda
  SoftPlusCuda
  AffineCuda
  SoftPlusCuda
  AffineCuda
  SoftPlusCuda
  AffineCuda
  SoftPlusCuda
  ConcatenateCuda
  MulScalarCuda
  AffineCuda
  SoftPlusCuda
  AffineCuda
  SoftPlusCuda
  AffineCuda
  SoftPlusCuda
  AffineCuda
  SliceCuda
  ReshapeCuda
  Callback
  Callback
  Callback
  MulScalarCuda
  SigmoidCudaCudnn
  Mul2Cuda
  Callback
  MulScalarCuda
  SigmoidCudaCudnn
  Mul2Cuda
  Callback
  MulScalarCuda
  SigmoidCudaCudnn
  Mul2Cuda
  Callback
  MulScalarCuda
  Callback
  AddScalarCuda
  MulScalarCuda
  SigmoidCudaCudnn
  Mul2Cuda
  Callback
  MulScalarCuda
  SigmoidCudaCudnn
  Mul2Cuda
  Callback
  MulScalarCuda
  SigmoidCudaCudnn
  Mul2Cuda
  Callback
  MulScalarCuda
  SigmoidCudaCudnn
  Mul2Cuda
  Callback
  Add2CudaCudnn
  Callback
  Callback
  Callback
  Add2CudaCudnn
  MulScalarCuda
  SinCuda
  Mul2Cuda
  AddScalarCuda
  CosCuda
  Mul2Cuda
  Add2CudaCudnn
  ReshapeCuda
  Mul2Cuda
  SumCuda
  ReshapeCuda
  Add2CudaCudnn
  Mul2Cuda
  SumCuda
  MulScalarCuda
  MulScalarCuda
  AddScalarCuda
  ReLUCuda
  ReshapeCuda
  RSubScalarCuda
  Mul2Cuda
  MulScalarCuda
  ReLUCuda
  Mul2Cuda
  Add2CudaCudnn
  MulScalarCuda
  SliceCuda
  SliceCuda
  Sub2Cuda
  Mul2Cuda
  MulScalarCuda
  Sub2Cuda
  Mul2Cuda
  SigmoidCudaCudnn
  Mul2Cuda
  MulScalarCuda
  Add2CudaCudnn
  Mul2Cuda
  SigmoidCudaCudnn
  Sub2Cuda
  AddScalarCuda
  AddScalarCuda
  Div2Cuda
  MaximumScalarCuda
  MinimumScalarCuda
  Mul2Cuda
  ReshapeCuda
  ReshapeCuda
  Mul2Cuda
  ReshapeCuda
  CosCuda
  SinCuda
  ConcatenateCuda
  AffineCuda
  SoftPlusCuda
  AffineCuda
  SoftPlusCuda
  AffineCuda
  SoftPlusCuda
  AffineCuda
  SliceCuda
  SoftPlusCuda
  MulScalarCuda
  SliceCuda
  SliceCuda
  Sub2Cuda
  Mul2Cuda
  ExpCuda
  RSubScalarCuda
  ConcatenateCuda
  RSubScalarCuda
  CumProdCuda
  Mul2Cuda
  SliceCuda
  SliceCuda
  ConcatenateCuda
  AffineCuda
  SoftPlusCuda
  AffineCuda
  SoftPlusCuda
  AffineCuda
  SoftPlusCuda
  AffineCuda
  SigmoidCudaCudnn
  ReshapeCuda
  MulScalarCuda
  BroadcastCuda
  ReshapeCuda
  ReshapeCuda
  Mul2Cuda
  ReshapeCuda
  CosCuda
  SinCuda
  ConcatenateCuda
  ReshapeCuda
  Sub2Cuda
  NormCuda
  PowScalarCuda
  AddScalarCuda
  RDivScalarCuda
  ConcatenateCuda
  AffineCuda
  SoftPlusCuda
  AffineCuda
  SoftPlusCuda
  AffineCuda
  SoftPlusCuda
  AffineCuda
  Mul2Cuda
  SigmoidCudaCudnn
  Mul2Cuda
  Mul2Cuda
  SumCuda
  Mul2Cuda
  SumCuda
  ReshapeCuda
  BroadcastCuda
  Mul2Cuda
  SumCuda
  AddScalarCuda
  NormCuda
  Div2Cuda
  RandCuda
  RandCuda
  Callback
  ReshapeCuda
  ReshapeCuda
  Mul2Cuda
  ReshapeCuda
  CosCuda
  SinCuda
  ConcatenateCuda
  Mul2Cuda
  SumCuda
  ReshapeCuda
  BroadcastCuda
  SliceCuda
  ReshapeCuda
  BroadcastCuda
  ConcatenateCuda
  AffineCuda
  SoftPlusCuda
  AffineCuda
  SoftPlusCuda
  AffineCuda
  SoftPlusCuda
  AffineCuda
  SigmoidCudaCudnn
  ReshapeCuda
  ReshapeCuda
  Mul2Cuda
  ReshapeCuda
  CosCuda
  SinCuda
  ConcatenateCuda
  AffineCuda
  SoftPlusCuda
  AffineCuda
  SoftPlusCuda
  AffineCuda
  SoftPlusCuda
  AffineCuda
  SoftPlusCuda
  Mul2Cuda
  SliceCuda
  ReshapeCuda
  BroadcastCuda
  Mul2Cuda
  SumCuda
  ReshapeCuda
  MaximumScalarCuda
  Mul2Cuda
  MeanCudaCudnn
  ConcatenateCuda
  AffineCuda
  SoftPlusCuda
  AffineCuda
  SoftPlusCuda
  AffineCuda
  SoftPlusCuda
  AffineCuda
  SigmoidCudaCudnn
  Mul2Cuda
  SumCuda
  Add2CudaCudnn
  Mul2Cuda
  Mul2Cuda
  SumCuda
  ReshapeCuda
  BroadcastCuda
  RandCuda
  RandCuda
  ConcatenateCuda
  AffineCuda
  SoftPlusCuda
  AffineCuda
  SoftPlusCuda
  AffineCuda
  SoftPlusCuda
  AffineCuda
  SliceCuda
  SigmoidCudaCudnn
  PowScalarCuda
  MaximumScalarCuda
  MinimumScalarCuda
  Mul2Cuda
  SumCuda
  Callback
  Mul2Cuda
  SumCuda
  ReshapeCuda
  MaximumScalarCuda
  ReshapeCuda
  BroadcastCuda
  PowScalarCuda
  RSubScalarCuda
  PowScalarCuda
  Mul2Cuda
  Add2CudaCudnn
  PowScalarCuda
  Add2CudaCudnn
  AddScalarCuda
  RDivScalarCuda
  ReshapeCuda
  BroadcastCuda
  Mul2Cuda
  SumCuda
  ReshapeCuda
  MaximumScalarCuda
  RSubScalarCuda
  PowScalarCuda
  Mul2Cuda
  Add2CudaCudnn
  PowScalarCuda
  Add2CudaCudnn
  AddScalarCuda
  RDivScalarCuda
  Mul2Cuda
  ConcatenateCuda
  AffineCuda
  SoftPlusCuda
  AffineCuda
  SoftPlusCuda
  AffineCuda
  SoftPlusCuda <-- ERROR
Error executing job with overrides: ['device_id=0', 'monitor_base_path=/media/veilytech/disk1/Code/NDJIR/outputs', 'data_path=/media/veilytech/disk1/Code/NDJIR/data/DTU/scan69']
Traceback (most recent call last):
  File "python/train.py", line 135, in main
    loss.forward(clear_no_need_grad=True)
  File "_variable.pyx", line 582, in nnabla._variable.Variable.forward
RuntimeError: memory error in alloc
/home/gitlab-runner/builds/LRsSYq-B/0/nnabla/builders/all/nnabla/src/nbla/memory/memory.cpp:39
Failed `this->alloc_impl()`: N4nbla10CudaMemoryE allocation failed.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by KazukiYoshiyama-sony** [comment]
Thank you for the trial. 

According error message, I guess you use GPU w/ less memory. Voxel grid feature uses memory proportional to the grid size. Please try with small grid size if your GPU has not sufficient memory.

**Comment by CuiYan27** [comment]
Thanks for your reply!

I tried to set my batch size to 1 and it is now running!
